/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaLoansRouteImport } from './routes/va-loans'
import { Route as ReverseMortgagesRouteImport } from './routes/reverse-mortgages'
import { Route as PnlLoansRouteImport } from './routes/pnl-loans'
import { Route as HelocRouteImport } from './routes/heloc'
import { Route as FixedSecondMortgageRouteImport } from './routes/fixed-second-mortgage'
import { Route as FhaLoansRouteImport } from './routes/fha-loans'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DscrLoansRouteImport } from './routes/dscr-loans'
import { Route as ConventionalLoansRouteImport } from './routes/conventional-loans'
import { Route as CommercialLoansRouteImport } from './routes/commercial-loans'
import { Route as BankStatementLoansRouteImport } from './routes/bank-statement-loans'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const VaLoansRoute = VaLoansRouteImport.update({
  id: '/va-loans',
  path: '/va-loans',
  getParentRoute: () => rootRouteImport,
} as any)
const ReverseMortgagesRoute = ReverseMortgagesRouteImport.update({
  id: '/reverse-mortgages',
  path: '/reverse-mortgages',
  getParentRoute: () => rootRouteImport,
} as any)
const PnlLoansRoute = PnlLoansRouteImport.update({
  id: '/pnl-loans',
  path: '/pnl-loans',
  getParentRoute: () => rootRouteImport,
} as any)
const HelocRoute = HelocRouteImport.update({
  id: '/heloc',
  path: '/heloc',
  getParentRoute: () => rootRouteImport,
} as any)
const FixedSecondMortgageRoute = FixedSecondMortgageRouteImport.update({
  id: '/fixed-second-mortgage',
  path: '/fixed-second-mortgage',
  getParentRoute: () => rootRouteImport,
} as any)
const FhaLoansRoute = FhaLoansRouteImport.update({
  id: '/fha-loans',
  path: '/fha-loans',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DscrLoansRoute = DscrLoansRouteImport.update({
  id: '/dscr-loans',
  path: '/dscr-loans',
  getParentRoute: () => rootRouteImport,
} as any)
const ConventionalLoansRoute = ConventionalLoansRouteImport.update({
  id: '/conventional-loans',
  path: '/conventional-loans',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialLoansRoute = CommercialLoansRouteImport.update({
  id: '/commercial-loans',
  path: '/commercial-loans',
  getParentRoute: () => rootRouteImport,
} as any)
const BankStatementLoansRoute = BankStatementLoansRouteImport.update({
  id: '/bank-statement-loans',
  path: '/bank-statement-loans',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bank-statement-loans': typeof BankStatementLoansRoute
  '/commercial-loans': typeof CommercialLoansRoute
  '/conventional-loans': typeof ConventionalLoansRoute
  '/dscr-loans': typeof DscrLoansRoute
  '/faq': typeof FaqRoute
  '/fha-loans': typeof FhaLoansRoute
  '/fixed-second-mortgage': typeof FixedSecondMortgageRoute
  '/heloc': typeof HelocRoute
  '/pnl-loans': typeof PnlLoansRoute
  '/reverse-mortgages': typeof ReverseMortgagesRoute
  '/va-loans': typeof VaLoansRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bank-statement-loans': typeof BankStatementLoansRoute
  '/commercial-loans': typeof CommercialLoansRoute
  '/conventional-loans': typeof ConventionalLoansRoute
  '/dscr-loans': typeof DscrLoansRoute
  '/faq': typeof FaqRoute
  '/fha-loans': typeof FhaLoansRoute
  '/fixed-second-mortgage': typeof FixedSecondMortgageRoute
  '/heloc': typeof HelocRoute
  '/pnl-loans': typeof PnlLoansRoute
  '/reverse-mortgages': typeof ReverseMortgagesRoute
  '/va-loans': typeof VaLoansRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bank-statement-loans': typeof BankStatementLoansRoute
  '/commercial-loans': typeof CommercialLoansRoute
  '/conventional-loans': typeof ConventionalLoansRoute
  '/dscr-loans': typeof DscrLoansRoute
  '/faq': typeof FaqRoute
  '/fha-loans': typeof FhaLoansRoute
  '/fixed-second-mortgage': typeof FixedSecondMortgageRoute
  '/heloc': typeof HelocRoute
  '/pnl-loans': typeof PnlLoansRoute
  '/reverse-mortgages': typeof ReverseMortgagesRoute
  '/va-loans': typeof VaLoansRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bank-statement-loans'
    | '/commercial-loans'
    | '/conventional-loans'
    | '/dscr-loans'
    | '/faq'
    | '/fha-loans'
    | '/fixed-second-mortgage'
    | '/heloc'
    | '/pnl-loans'
    | '/reverse-mortgages'
    | '/va-loans'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bank-statement-loans'
    | '/commercial-loans'
    | '/conventional-loans'
    | '/dscr-loans'
    | '/faq'
    | '/fha-loans'
    | '/fixed-second-mortgage'
    | '/heloc'
    | '/pnl-loans'
    | '/reverse-mortgages'
    | '/va-loans'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/bank-statement-loans'
    | '/commercial-loans'
    | '/conventional-loans'
    | '/dscr-loans'
    | '/faq'
    | '/fha-loans'
    | '/fixed-second-mortgage'
    | '/heloc'
    | '/pnl-loans'
    | '/reverse-mortgages'
    | '/va-loans'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BankStatementLoansRoute: typeof BankStatementLoansRoute
  CommercialLoansRoute: typeof CommercialLoansRoute
  ConventionalLoansRoute: typeof ConventionalLoansRoute
  DscrLoansRoute: typeof DscrLoansRoute
  FaqRoute: typeof FaqRoute
  FhaLoansRoute: typeof FhaLoansRoute
  FixedSecondMortgageRoute: typeof FixedSecondMortgageRoute
  HelocRoute: typeof HelocRoute
  PnlLoansRoute: typeof PnlLoansRoute
  ReverseMortgagesRoute: typeof ReverseMortgagesRoute
  VaLoansRoute: typeof VaLoansRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/va-loans': {
      id: '/va-loans'
      path: '/va-loans'
      fullPath: '/va-loans'
      preLoaderRoute: typeof VaLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reverse-mortgages': {
      id: '/reverse-mortgages'
      path: '/reverse-mortgages'
      fullPath: '/reverse-mortgages'
      preLoaderRoute: typeof ReverseMortgagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pnl-loans': {
      id: '/pnl-loans'
      path: '/pnl-loans'
      fullPath: '/pnl-loans'
      preLoaderRoute: typeof PnlLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heloc': {
      id: '/heloc'
      path: '/heloc'
      fullPath: '/heloc'
      preLoaderRoute: typeof HelocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixed-second-mortgage': {
      id: '/fixed-second-mortgage'
      path: '/fixed-second-mortgage'
      fullPath: '/fixed-second-mortgage'
      preLoaderRoute: typeof FixedSecondMortgageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fha-loans': {
      id: '/fha-loans'
      path: '/fha-loans'
      fullPath: '/fha-loans'
      preLoaderRoute: typeof FhaLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dscr-loans': {
      id: '/dscr-loans'
      path: '/dscr-loans'
      fullPath: '/dscr-loans'
      preLoaderRoute: typeof DscrLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conventional-loans': {
      id: '/conventional-loans'
      path: '/conventional-loans'
      fullPath: '/conventional-loans'
      preLoaderRoute: typeof ConventionalLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial-loans': {
      id: '/commercial-loans'
      path: '/commercial-loans'
      fullPath: '/commercial-loans'
      preLoaderRoute: typeof CommercialLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-statement-loans': {
      id: '/bank-statement-loans'
      path: '/bank-statement-loans'
      fullPath: '/bank-statement-loans'
      preLoaderRoute: typeof BankStatementLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BankStatementLoansRoute: BankStatementLoansRoute,
  CommercialLoansRoute: CommercialLoansRoute,
  ConventionalLoansRoute: ConventionalLoansRoute,
  DscrLoansRoute: DscrLoansRoute,
  FaqRoute: FaqRoute,
  FhaLoansRoute: FhaLoansRoute,
  FixedSecondMortgageRoute: FixedSecondMortgageRoute,
  HelocRoute: HelocRoute,
  PnlLoansRoute: PnlLoansRoute,
  ReverseMortgagesRoute: ReverseMortgagesRoute,
  VaLoansRoute: VaLoansRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
