/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PnlLoansRouteImport } from './routes/pnl-loans'
import { Route as HelocRouteImport } from './routes/heloc'
import { Route as FixedSecondMortgageRouteImport } from './routes/fixed-second-mortgage'
import { Route as DscrLoansRouteImport } from './routes/dscr-loans'
import { Route as BankStatementLoansRouteImport } from './routes/bank-statement-loans'
import { Route as IndexRouteImport } from './routes/index'

const PnlLoansRoute = PnlLoansRouteImport.update({
  id: '/pnl-loans',
  path: '/pnl-loans',
  getParentRoute: () => rootRouteImport,
} as any)
const HelocRoute = HelocRouteImport.update({
  id: '/heloc',
  path: '/heloc',
  getParentRoute: () => rootRouteImport,
} as any)
const FixedSecondMortgageRoute = FixedSecondMortgageRouteImport.update({
  id: '/fixed-second-mortgage',
  path: '/fixed-second-mortgage',
  getParentRoute: () => rootRouteImport,
} as any)
const DscrLoansRoute = DscrLoansRouteImport.update({
  id: '/dscr-loans',
  path: '/dscr-loans',
  getParentRoute: () => rootRouteImport,
} as any)
const BankStatementLoansRoute = BankStatementLoansRouteImport.update({
  id: '/bank-statement-loans',
  path: '/bank-statement-loans',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bank-statement-loans': typeof BankStatementLoansRoute
  '/dscr-loans': typeof DscrLoansRoute
  '/fixed-second-mortgage': typeof FixedSecondMortgageRoute
  '/heloc': typeof HelocRoute
  '/pnl-loans': typeof PnlLoansRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bank-statement-loans': typeof BankStatementLoansRoute
  '/dscr-loans': typeof DscrLoansRoute
  '/fixed-second-mortgage': typeof FixedSecondMortgageRoute
  '/heloc': typeof HelocRoute
  '/pnl-loans': typeof PnlLoansRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bank-statement-loans': typeof BankStatementLoansRoute
  '/dscr-loans': typeof DscrLoansRoute
  '/fixed-second-mortgage': typeof FixedSecondMortgageRoute
  '/heloc': typeof HelocRoute
  '/pnl-loans': typeof PnlLoansRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bank-statement-loans'
    | '/dscr-loans'
    | '/fixed-second-mortgage'
    | '/heloc'
    | '/pnl-loans'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bank-statement-loans'
    | '/dscr-loans'
    | '/fixed-second-mortgage'
    | '/heloc'
    | '/pnl-loans'
  id:
    | '__root__'
    | '/'
    | '/bank-statement-loans'
    | '/dscr-loans'
    | '/fixed-second-mortgage'
    | '/heloc'
    | '/pnl-loans'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BankStatementLoansRoute: typeof BankStatementLoansRoute
  DscrLoansRoute: typeof DscrLoansRoute
  FixedSecondMortgageRoute: typeof FixedSecondMortgageRoute
  HelocRoute: typeof HelocRoute
  PnlLoansRoute: typeof PnlLoansRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pnl-loans': {
      id: '/pnl-loans'
      path: '/pnl-loans'
      fullPath: '/pnl-loans'
      preLoaderRoute: typeof PnlLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heloc': {
      id: '/heloc'
      path: '/heloc'
      fullPath: '/heloc'
      preLoaderRoute: typeof HelocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixed-second-mortgage': {
      id: '/fixed-second-mortgage'
      path: '/fixed-second-mortgage'
      fullPath: '/fixed-second-mortgage'
      preLoaderRoute: typeof FixedSecondMortgageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dscr-loans': {
      id: '/dscr-loans'
      path: '/dscr-loans'
      fullPath: '/dscr-loans'
      preLoaderRoute: typeof DscrLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-statement-loans': {
      id: '/bank-statement-loans'
      path: '/bank-statement-loans'
      fullPath: '/bank-statement-loans'
      preLoaderRoute: typeof BankStatementLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BankStatementLoansRoute: BankStatementLoansRoute,
  DscrLoansRoute: DscrLoansRoute,
  FixedSecondMortgageRoute: FixedSecondMortgageRoute,
  HelocRoute: HelocRoute,
  PnlLoansRoute: PnlLoansRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
